import bcrypt from "bcryptjs";
import { Request, Response } from "express";
import { User } from "../models/User";
import { env } from "../config/env";
import { signToken } from "../utils/auth";
function setAuthCookie(res:Response,token:string){const production=env.NODE_ENV==="production";res.cookie(env.COOKIE_NAME,token,{httpOnly:true,secure:production,sameSite:production?"none":"lax",maxAge:7*24*60*60*1000,path:"/"});}
function publicUser(user:any){return {id:String(user._id),_id:String(user._id),name:user.name,email:user.email,role:user.role,accountStatus:user.accountStatus,verified:user.verified,phone:user.phone};}
export async function login(req:Request,res:Response){const email=String(req.body?.email??"").trim().toLowerCase(),password=String(req.body?.password??"");if(!email||!password)return res.status(400).json({message:"Email and password are required."});const user=await User.findOne({email}).select("+passwordHash");if(!user||!user.passwordHash||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({message:"Invalid email or password."});if(user.accountStatus!=="active")return res.status(403).json({message:"This account is not active."});setAuthCookie(res,signToken({userId:String(user._id),role:user.role}));return res.json({success:true,user:publicUser(user)});}
export async function googleLogin(req:Request,res:Response){const credential=String(req.body?.credential??"");if(!credential)return res.status(400).json({message:"Google credential is required."});if(!env.GOOGLE_CLIENT_ID)return res.status(503).json({message:"Google login is not configured on the server."});const googleRes=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(credential)}`);if(!googleRes.ok)return res.status(401).json({message:"Invalid Google sign-in token."});const payload:any=await googleRes.json();if(payload.aud!==env.GOOGLE_CLIENT_ID||!payload.email||payload.email_verified!=="true"||payload.iss!=="https://accounts.google.com")return res.status(401).json({message:"Google account verification failed."});const email=String(payload.email).toLowerCase();let user=await User.findOne({email});if(!user){user=await User.create({name:payload.name||email.split("@")[0],email,passwordHash:await bcrypt.hash(`${Math.random().toString(36)}-${Date.now()}`,12),role:"USER",verified:true,accountStatus:"active"});}else if(user.accountStatus!=="active")return res.status(403).json({message:"This account is not active."});user.verified=true;await user.save();setAuthCookie(res,signToken({userId:String(user._id),role:user.role}));return res.json({success:true,user:publicUser(user)});}
export async function logout(_req:Request,res:Response){const production=env.NODE_ENV==="production";res.clearCookie(env.COOKIE_NAME,{httpOnly:true,secure:production,sameSite:production?"none":"lax",path:"/"});return res.json({success:true,message:"Logged out successfully."});}
export async function register(req:Request,res:Response){const name=String(req.body?.name??"").trim(),email=String(req.body?.email??"").trim().toLowerCase(),password=String(req.body?.password??""),phone=req.body?.phone?String(req.body.phone).trim():undefined;if(name.length<2||!email||password.length<8)return res.status(400).json({message:"Name, valid email and a password of at least 8 characters are required."});if(await User.findOne({email}))return res.status(409).json({message:"An account with this email already exists."});const user=await User.create({name,email,phone,passwordHash:await bcrypt.hash(password,12),role:"USER",verified:true,accountStatus:"active"});setAuthCookie(res,signToken({userId:String(user._id),role:user.role}));return res.status(201).json({success:true,user:publicUser(user)});}
export async function me(req:any,res:Response){const userId=req.user?.userId;if(!userId)return res.status(401).json({message:"Authentication required."});const user=await User.findById(userId).select("-passwordHash");if(!user)return res.status(404).json({message:"User not found."});if(user.accountStatus!=="active")return res.status(403).json({message:"This account is not active."});return res.json({success:true,user:publicUser(user)});}
